# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf1cb9e5c382fc429298d5e92f3eaf26e902644803fd76717ddc222d50734cf1b9511035f6a2a4af2784bd90e5e327bfd0e50d1ca33c091153f1f31ee287a64

test:
  secret_key_base: 923919885a5f096bf45a8de0f1cdfd5882c64a85b912bf5d462de22c8dbf95a4051f4cd71c0a4e6890724f4b109b2aae9d186b46c13c8cd56c8111202d504cd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
